### ISSUE TITLE
Error running FUSTr

### ISSUE THREAD

**Issue by koushikPCR** [tijeco/FUSTr#2]
Hi, 
    I am running FUSTr on my transcriptome datasets. I am running it on my local machine as docker is failing to run. I am getting the following error message, but all the dependencies seems to be fine. 

Traceback (most recent call last):
  File "/home/uom/FUSTr/bin/FUSTr", line 135, in <module>
    output = subprocess.check_output(['bash','-c', bashCommand])
  File "/home/uom/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/uom/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '-c', 'snakemake --snakefile $(which FUSTrSnakefile) -d /home/uom/FUSTr/Nas --cores 16 --use-conda --configfile configure.json']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/uom/FUSTr/bin/FUSTr", line 144, in <module>
    output = subprocess.check_output(['bash','-c', bashCommand])
  File "/home/uom/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/uom/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '-c', 'snakemake --snakefile $(which FUSTrSnakefile) -d /home/uom/FUSTr/Nas --cores 16 --use-conda --configfile configure.json']' returned non-zero exit status 1.

I also have one more clarification to be made regarding the usage. I have 2 parental transcriptomes and 3 hybrid transcriptomes. Is it fine if I run FUSTr on individual samples? Or does FUSTr needs more than one dataset for comparisons?

**Comment by stupornova33** [comment]
Hi, 
Did you ever solve this issue? I'm getting the same error just running on 6 transcriptomes.

**Comment by koushik1989** [comment]
> Hi,
> Did you ever solve this issue? I'm getting the same error just running on 6 transcriptomes.

Hi I am attaching all the replies I received from the author.
reply to my query
1. **Thanks Koushik, I recently made some updates to FUSTr so it's likely that a bug was introduced that I haven't caught yet. I will take a look into this and get back to you.**

_The author took a look at my inputs and sent the following reply._

**I believe I have figured it out. FUSTr only analyzes gene families with 15 or more sequences, and the largest gene family in your dataset contained 12 sequences and that's only one family. If you provided it with more data from other samples it may be able to infer larger families. Typically, FUSTr works quite well with finding multigene families from transcriptomes from several closely related species.**

Subsequently I abandoned FUSTr and moved on from gene family level analysis. 
Thanks.

**Comment by apollomarco** [comment]
Hi! Any updates on this error? I get almost the same error. 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/apl/miniconda3/bin/FUSTr", line 141, in <module>
    output = subprocess.check_output(['bash','-c', bashCommand])
  File "/home/apl/miniconda3/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/apl/miniconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '-c', 'snakemake --snakefile $(which FUSTrSnakefile) -d /home/apl/trinityrnaseq-v2.9.1/Docker/CroCo/Calanus_dataset --cores 10 --use-conda --configfile configure.json  --unlock']' returned non-zero exit status 2.


Thanks!
